name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-22.04
    steps:
      - uses: kawamataryo/lapras-card-readme@v1.2.1
        with:
          SHARE_ID: takayuki818
          ICON_FIRST: "#212121"
          ICON_SECOND: "#818181"
          BACKGROUND_FIRST: "#232323"
          BACKGROUND_SECOND: "#6d6d6d"
          LANG: "en"
          CARD_WIDTH: "40%"
          UPDATE_TIME: "false"
          # 以下オプション
          # https://lapras-card-generator.vercel.app でカスタマイズしたデザインを設定可能
          # ICON_FIRST: "#030E21"
          # ICON_SECOND: "#1688BF"
          # BACKGROUND_FIRST: "#020E27"
          # BACKGROUND_SECOND: "#0E5593"
          # LANG: "ja"
          # CARD_WIDTH: "400"
          # UPDATE_TIME: "true"
          # README_FILE: "README.md"
          # IS_CENTER: "true"
          # ALTERNATIVE_TEXT: "Score of {SHARE_ID} on LAPRAS"
